---
- name: install marathon
  apt: name=marathon state=present

- name: create conf directory
  shell: sudo mkdir -p /etc/marathon/conf

- name: set hostname
  template: src=hostname.j2 dest=/etc/marathon/conf/hostname

- name: set marathon zookeeper configuration
  template: src=master.j2 dest=/etc/marathon/conf/master

- name: copy zookeeper marathon configuration file
  template: src=zk.j2 dest=/etc/marathon/conf/zk

- name: start marathon
  service: name=marathon state=restarted enabled=yes
