---
- name: create sudo user
  user: name=mesos
        groups=sudo
        shell=/bin/bash
        generate_ssh_key=no
        state=present

- name: remove mesos sudo passwd
  copy: src=mesos
        dest=/etc/sudoers.d
        mode=0440
