---
- name: setup zk configuration file
  template: src=zk.j2 dest=/etc/mesos/zk

- name: set mesos slave ip
  template: src=ip.j2 dest=/etc/mesos-slave/ip

- name: set mesos slave hostname
  template: src=hostname.j2 dest=/etc/mesos-slave/hostname

- name: make sure zookeper is stopped
  service: name=zookeeper state=stopped
  ignore_errors: yes

- name: prevent zookeeper from running
  shell: echo manual | sudo tee /etc/init/zookeeper.override

- name: make sure mesos master is stopped
  service: name=mesos-master state=stopped
  ignore_errors: yes

- name: ensure mesos master will not start on reboot
  shell: echo manual | sudo tee /etc/init/mesos-master.override

- name: install docker package
  shell: sudo curl -sSL https://get.docker.com/ | sh
  # shell: sudo wget -qO- https://get.docker.com/ | sh
  ignore_errors: yes

- name: configure containerizers
  shell: echo 'docker,mesos' | sudo tee /etc/mesos-slave/containerizers

- name: start docker
  service: name=docker state=restarted enabled=yes
  ignore_errors: yes

- name: make sure mesos-slave is running
  service: name=mesos-slave state=restarted enabled=yes
