---
- name: import Mesosphere key
  shell: sudo apt-key adv --keyserver keyserver.ubuntu.com --recv E56151BF

- name: update sources list
  shell: DISTRO=$(lsb_release -is | tr '[:upper:]' '[:lower:]') && CODENAME=$(lsb_release -cs) && echo "deb http://repos.mesosphere.io/${DISTRO} ${CODENAME} main" | sudo tee /etc/apt/sources.list.d/mesosphere.list

- name: update packages
  apt: update_cache=yes cache_valid_time=3600

- name: install mesos + zookeeper
  apt: name=mesos state=present
