---
- name: setup zk configuration file
  template: src=zk.j2 dest=/etc/mesos/zk

- name: set mesos master ip
  template: src=ip.j2 dest=/etc/mesos-master/ip

- name: set mesos master hostname
  template: src=hostname.j2 dest=/etc/mesos-master/hostname

- name: set mesos master quorum to 2
  template: src=quorum.j2 dest=/etc/mesos-master/quorum

- name: set cluster name
  template: src=cluster.j2 dest=/etc/mesos-master/cluster

- name: stop mesos slave
  service: name=mesos-slave state=stopped
  ignore_errors: yes

- name: prevent mesos-slave from running
  shell: echo manual | sudo tee /etc/init/mesos-slave.override

- name: start mesos-master
  service: name=mesos-master state=restarted enabled=yes
