---
- name: install mesosphere (mesos + zookeeper + marathon)
  apt: name=mesosphere state=present

- name: copy zookeeper mesos configuration file
  shell: cp /tmp/zk_mesos /etc/mesos/zk

- name: copy zookeeper myid configuration file
  template: src=zk_myid.j2 dest=/etc/zookeeper/conf/myid

- name: copy zookeeper hosts configuration
  template: src=zk_cfg.j2 dest=/etc/zookeeper/conf/zoo.cfg

- name: set mesos master quorum to 2
  copy: src=quorum dest=/etc/mesos-master/quorum

- name: set mesos master ip
  template: src=ip.j2 dest=/etc/mesos-master/ip

- name: set mesos master hostname
  template: src=hostname.j2 dest=/etc/mesos-master/hostname

- name: set marathon hostname
  shell: sudo mkdir -p /etc/marathon/conf && sudo cp /etc/mesos-master/hostname /etc/marathon/conf

- name: set marathon zookeeper configuration
  shell: cp /etc/mesos/zk /etc/marathon/conf/master

- name: copy zookeeper marathon configuration file
  template: src=zk_marathon.j2 dest=/etc/marathon/conf/zk

- name: stop mesos slave
  service: name=mesos-slave state=stopped
  ignore_errors: yes

- name: prevent mesos-salve from running
  shell: echo manual | sudo tee /etc/init/mesos-slave.override

- name: restart zookeper
  service: name=zookeeper state=restarted 

- name: restart mesos-master
  service: name=mesos-master state=restarted
  # shell: sudo restart mesos-master

- name: restart marathon
  service: name=marathon state=restarted 

- name: start chronos
  service: name=chronos state=restarted enabled=yes
